### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by Thesyjaga** [MaxxRK/chaseinvest-api#37]
I have a problem where it gives me this screen and the program cannot click on the trade button because I have more then 5 accounts. Is there any fix for this?
btw when I click the 3 dot next to account then only is giving to option for "trade"
![Screenshot 2024-05-09 154913](https://github.com/MaxxRK/chaseinvest-api/assets/167492583/c6d61e5b-95aa-446f-b4f3-fbfce84bf99a)

**Comment by MaxxRK** [comment]
This api does not click on the trade button. I have more than five accounts as well.

**Comment by MaxxRK** [comment]
Can you post the output in the cli?

**Comment by Thesyjaga** [comment]
what do you mean by "output in the cli"

**Comment by Thesyjaga** [comment]
It process in 1 account then it gets to the second account but it doesn't place the order. 

This is the error I am getting 


C:\Users\thesy>py Documents/Python/Chase/main.py
Login succeeded without needing 2fa...
Options:
1. Buy
2. Sell
Enter your choice (1 for BUY or 2 for SELL): 1
Enter the stock ticker: tirx
Enter the quantity: 1
Error finding or typing in the search input field: Timeout 30000ms exceeded.
Success We'll process order !!!!!! the next business day before the market opens. Please check your order status for updates.
Error finding or typing in the search input field: Timeout 30000ms exceeded.
Traceback (most recent call last):
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\chase\order.py", line 264, in place_order
    self.session.page.click("#submitOrder", timeout=10000)
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 9466, in click
    self._sync(
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 113, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_page.py", line 753, in click
    return await self._main_frame.click(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 509, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.TimeoutError: Timeout 10000ms exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thesy\Documents\Python\Chase\main.py", line 70, in <module>
    order_messages = order_module.place_order(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thesy\AppData\Local\Programs\Python\Python312\Lib\site-packages\chase\order.py", line 266, in place_order
    raise Exception("No place order button found cannot continue.")
Exception: No place order button found cannot continue.

**Comment by Thesyjaga** [comment]
Btw this is my code

import sys
import yfinance as yf  
from chase import account as acc
from chase import order 
from chase import session
from playwright.sync_api import sync_playwright

# Function to get the current price of a stock using yfinance
def get_current_price(stock_symbol):
    stock_data = yf.Ticker(stock_symbol)
    current_price = stock_data.history(period="1d")["Close"].iloc[-1]
    return current_price

# Create Session
cs = session.ChaseSession(title="ChaseProfile", headless=False, profile_path='./chase_profile')

# Login to Chase.com
login_one = cs.login("...", "..", "....")

if not login_one:
    print('Login succeeded without needing 2fa...')
else:
    code = input('Please input code that was sent to your phone: ')
    login_two = cs.login_two(code)

all_accounts = acc.AllAccount(cs)

if all_accounts.account_connectors is None:
    sys.exit("Failed to get account connectors, exiting script...")

account_ids = list(all_accounts.account_connectors.keys())

# Display options
print("Options:")
print("1. Buy")
print("2. Sell")
choice = input("Enter your choice (1 for BUY or 2 for SELL): ")

if choice == "1":
    buy_or_sell = "BUY"
elif choice == "2":
    buy_or_sell = "SELL"
else:
    sys.exit("Invalid choice. Please enter '1' for BUY or '2' for SELL.")

stock_symbol = input("Enter the stock ticker: ")
quantity = int(input("Enter the quantity: "))

# Get the current price of the stock
current_price = get_current_price(stock_symbol)

# Adjust price based on buy/sell action
if buy_or_sell == "BUY":
    current_price += 0.01
else:
    current_price -= 0.01

current_price = round(current_price, 2)

# Place order for the specified stock symbol and quantity in all accounts
order_module = order.Order(cs)  # Creating an instance of Order
for account_id in account_ids:
    # Find the search input field and type the stock symbol
    try:
        search_input = cs.page.wait_for_selector('input[name="search"]')
        search_input.fill(stock_symbol)
    except Exception as e:
        print(f"Error finding or typing in the search input field: {e}")
    
    order_messages = order_module.place_order(
        account_id,
        quantity,
        order.PriceType.LIMIT,
        stock_symbol,
        order.Duration.DAY,
        order.OrderSide[buy_or_sell],
        limit_price=current_price,
        dry_run=False,
    )
    
    if order_messages["ORDER CONFIRMATION"] != "":
        print(order_messages["ORDER CONFIRMATION"])
    else:
        print(order_messages)

**Comment by MaxxRK** [comment]
It looks like you are trying to use the 'New trading experience'. You have to let the api switch itself back to the 'Old trading experience' or it will not work. If you update the package version to 0.1.4 it should do that automatically.

**Comment by Thesyjaga** [comment]
oh mb I have 0.13 installed not the 0.14

**Comment by Thesyjaga** [comment]
It now works! thank you
