### ISSUE TITLE
Unable to launch and click elements

### ISSUE THREAD

**Issue by kunal-122** [MaxxRK/chaseinvest-api#49]
![image](https://github.com/user-attachments/assets/9cf88467-58bd-4531-ad82-1a1d78dd963b)

Hi there, I am trying to run the code, but I get this error after the chase website just stays frozen/spinning.

The error associated is "waiting for locator("#signin-button") to be visible.

**Comment by MaxxRK** [comment]
you need to use a special version of playwright-stealth until I release a package.

run `pip install -e git+https://github.com/MaxxRK/playwright_stealth.git@a6688bb792395f182d22dff3e330400bb0df1eca#egg=playwright_stealth` the original playwright-stealth seems to have been abandoned right now. You may also need to run `playwright install firefox` after running this. It calls for a specific playwright version.

**Comment by kunal-122** [comment]
Awesome, thank you, that fixed it

**Comment by kunal-122** [comment]
Sorry to ask about this again, but do you know how I could apply this fix to the auto-rsa bot?

**Comment by kunal-122** [comment]
Transactions in the auto-rsa bot seems to being able to click, could this be due to the auto-rsa bot not being up to date with your latest changes?


`
==============================
auto-rsa      | Chase
auto-rsa      | ==============================
auto-rsa      | 
auto-rsa      | Traceback (most recent call last):
auto-rsa      |   File "/[app/helperAPI.py](http://app/helperAPI.py)", line 335, in _run
auto-rsa      |     result = self.func(*self.args, **self.kwargs)
auto-rsa      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
auto-rsa      |   File "/[app/chaseAPI.py](http://app/chaseAPI.py)", line 59, in chase_run
auto-rsa      |     chase_transaction(
auto-rsa      |   File "/[app/chaseAPI.py](http://app/chaseAPI.py)", line 244, in chase_transaction
auto-rsa      |     symbol_quote = symbols.SymbolQuote(
auto-rsa      |                    ^^^^^^^^^^^^^^^^^^^^
auto-rsa      |   File "/usr/local/lib/python3.12/site-packages/chase/symbols.py", line 62, in __init__
auto-rsa      |     self.get_symbol_quote()
auto-rsa      |   File "/usr/local/lib/python3.12/site-packages/chase/symbols.py", line 77, in get_symbol_quote
auto-rsa      |     experience.click()
auto-rsa      |   File "/usr/local/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 2001, in click
auto-rsa      |     self._sync(
auto-rsa      |   File "/usr/local/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
auto-rsa      |     return task.result()
auto-rsa      |            ^^^^^^^^^^^^^
auto-rsa      |   File "/usr/local/lib/python3.12/site-packages/playwright/_impl/_element_handle.py", line 132, in click
auto-rsa      |     await self._channel.send("click", locals_to_params(locals()))
auto-rsa      |   File "/usr/local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
auto-rsa      |     return await self._connection.wrap_api_call(
auto-rsa      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
auto-rsa      |   File "/usr/local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
auto-rsa      |     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
auto-rsa      | playwright._impl._errors.TimeoutError: ElementHandle.click: Timeout 30000ms exceeded.
auto-rsa      | Call log:
auto-rsa      | attempting click action
auto-rsa      |   -   waiting for element to be visible, enabled and stable
auto-rsa      |   -   element is visible, enabled and stable
auto-rsa      |   -   scrolling into view if needed
auto-rsa      |   -   done scrolling
auto-rsa      |   -   <div class="backdrop" role="presentation" data-testid="modalBackdrop"></div> from <div>…</div> subtree intercepts pointer events
- retrying click action, attempt #1
auto-rsa      |   -   waiting 500ms
auto-rsa      |   -   waiting for element to be visible, enabled and stable
auto-rsa      |   -   element is visible, enabled and stable
auto-rsa      |   -   scrolling into view if needed
auto-rsa      |   -   done scrolling
auto-rsa      |   -   <div class="backdrop" role="presentation" data-testid="modalBackdrop"></div> from <div>…</div> subtree intercepts pointer events
...
auto-rsa      |   - retrying click action, attempt #60
auto-rsa      |   -   waiting 500ms
auto-rsa      | 
auto-rsa      | None
auto-rsa      | Traceback (most recent call last):
auto-rsa      |   File "/[app/autoRSA.py](http://app/autoRSA.py)", line 167, in fun_run
auto-rsa      |     raise Exception(
auto-rsa      | Exception: Error in chase_run: Function did not complete successfully.`

**Comment by kunal-122** [comment]
I see now, thank you for all the help, hoping I can get it to work at some point haha
